steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/$PROJECT_ID/pm-light-agent:latest','.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/$PROJECT_ID/pm-light-agent:latest']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply','-f','infra/k8s-deployment.yaml']
images:
- 'gcr.io/$PROJECT_ID/pm-light-agent:latest'
